CREATE TABLE CLIENTEREGISTRATO(            
            NOME VARCHAR(255),
            COGNOME VARCHAR(255),
            VIA VARCHAR(255),
            NUMEROCIVICO INT NOT NULL,
            PROVINCIA VARCHAR(255),
            CITTA VARCHAR(255),
            EMAIL VARCHAR(255) PRIMARY KEY,
            USERNAME VARCHAR(255),
            PASSWORD VARCHAR(255),
	        CARTADICREDITO VARCHAR(255) NOT NULL
);


CREATE TABLE DIPENDENTE(
            NOME VARCHAR(255),
            COGNOME VARCHAR(255),
            CODFISCALE VARCHAR(16) PRIMARY KEY
);


CREATE TABLE SCONTO(
            IDSCONTO INT PRIMARY KEY,
            CODICE VARCHAR(255),
            PERCENTUALE INT
);

CREATE TABLE ACQUISTO(
            IDACQUISTO INT PRIMARY KEY,
            TOTALESPESA INT
);

INSERT INTO CLIENTEREGISTRATO VALUES ('Luigi','Esposito','Via Alcide de Gasperi', '110', 'Napoli', 'Scafati', 'gigiesposito09@gmail.com', 'gigiespo', '1g7e90', '5778899100991122');


INSERT INTO ACQUISTO VALUES(1, '100');


INSERT INTO SCONTO VALUES(1, 'HOLIDAY50','50');

INSERT INTO SCONTO VALUES(2, 'PROMO25','25');

INSERT INTO SCONTO VALUES(3, 'EASTER15','15');

